import { API_GATEWAY_NOTIFICATION_TO_NOTIFICATION_MICROSERVICE_KAFKA_REGISTRY, USER_MS_TO_PRODUCT_MICROSERVICE_KAFKA_REGISTRY } from "../../constant/kafka.registry";
import { NOTIFICATION_MICROSERVICE_TCP_REGISTRY, PRODUCT_MICROSERVICE_TCP_REGISTRY } from "../../constant/tcp.registry";

export const MODULE_CONFIG = {
  master_ms: {
  },
  PRODUCT_MS: {
    transport: process.env.PRODUCT_MICROSERVICE_TRANSPORT,
    TCP: PRODUCT_MICROSERVICE_TCP_REGISTRY,
    KAFKA: USER_MS_TO_PRODUCT_MICROSERVICE_KAFKA_REGISTRY,
    REDIS: {},
    RABBITMQ: {},
  },
  NOTIFICATION_MS: {
    transport: process.env.NOTIFICATION_MICROSERVICE_TRANSPORT,
    TCP: NOTIFICATION_MICROSERVICE_TCP_REGISTRY,
    KAFKA: API_GATEWAY_NOTIFICATION_TO_NOTIFICATION_MICROSERVICE_KAFKA_REGISTRY,
    REDIS: {},
    RABBITMQ: {},
  }
};
